In [1]:
import tensorflow as tf
import numpy as np
np.set_printoptions(precision=3)

2025-05-13 14:46:45.719205: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


#### Convert list/arrays to tensor

In [2]:
a = np.array([1,2,3], dtype=np.int32)
b = [4,5,6]

In [13]:
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)
print(t_a)
t_a.shape

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


TensorShape([3])

#### Get values from a tensor

In [ ]:
t_ones = tf.ones((2,3))
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

#### Change data type in a tensor

In [15]:
t_a_new = tf.cast(t_a, tf.int64)
t_a_new

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

#### Reshaping a tensor

In [16]:
t = tf.random.uniform(shape=(3,5))
t_tr = tf.transpose(t)
print(t.shape, '->', t_tr.shape)

(3, 5) -> (5, 3)


In [17]:
t = tf.zeros((30,))
t_reshape = tf.reshape(t, shape=(5,6))
print(t_reshape.shape)

(5, 6)


In [ ]:
t = tf.zeros((1,2,1,4,1))
t_sqz = tf.squeeze(t, axis=(2, 4))
print(t.shape, '->', t_sqz.shape)

(1, 2, 1, 4, 1) -> (1, 2, 4)


#### Mathmatical operation

In [26]:
tf.random.set_seed(1)
t1 = tf.random.uniform(shape=(5,2),
                       minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5,2),
                      mean=0.0, stddev=1.0)
t3 = tf.multiply(t1,t2).numpy()
print(t3)

[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]


In [28]:
t4 = tf.math.reduce_mean(t1, axis=0)
print(t4)

tf.Tensor([0.09  0.207], shape=(2,), dtype=float32)


In [ ]:
t5 = tf.linalg.matmul(t1, t2, transpose_b=True)
t5 = tf.linalg.matmul(t1, t2, transpose_a=True)
print(t5)

tf.Tensor(
[[-1.144  1.115 -0.87  -0.321  0.856]
 [ 0.248 -0.191  0.25  -0.064 -0.331]
 [-0.478  0.407 -0.436  0.022  0.527]
 [ 0.525 -0.234  0.741 -0.593 -1.194]
 [-0.099  0.26   0.125 -0.462 -0.396]], shape=(5, 5), dtype=float32)


In [31]:
norm_t1 = tf.norm(t1, ord=2, axis=1).numpy()
print(norm_t1)

[1.046 0.293 0.504 0.96  0.383]


In [34]:
tf.random.set_seed(1)
t = tf.random.uniform((6, ))
print(t.numpy())

[0.165 0.901 0.631 0.435 0.292 0.643]


In [37]:
# Split
t_splits = tf.split(t, num_or_size_splits=[4,2])
[item.numpy() for item in t_splits]

[array([0.165, 0.901, 0.631, 0.435], dtype=float32),
 array([0.292, 0.643], dtype=float32)]

In [45]:
# Concat
A = tf.ones((3,))
B = tf.zeros((2,))
C = tf.concat([A, B], axis=0)
print(C.numpy())


[1. 1. 1. 0. 0.]


In [47]:
D = tf.zeros((3,))
S = tf.stack([A, D], axis=1)
print(S.numpy())

[[1. 0.]
 [1. 0.]
 [1. 0.]]


#### Preprocessing in batches

In [58]:
a = tf.random.uniform((50,))
ds = tf.data.Dataset.from_tensor_slices(a)
ds_batch = ds.batch(8, drop_remainder=False) #can set `drop_remainder=True` if need to drop the last batch
for i, elem in enumerate(ds_batch,1): #make i starts from 1
    print(f"batch {i}, {elem.numpy()}")

batch 1, [0.506 0.945 0.221 0.26  0.581 0.166 0.958 0.178]
batch 2, [0.848 0.539 0.657 0.115 0.072 0.981 0.091 0.237]
batch 3, [0.69  0.194 0.198 0.16  0.638 0.098 0.794 0.69 ]
batch 4, [0.116 0.553 0.867 0.381 0.116 0.747 0.567 0.865]
batch 5, [0.776 0.17  0.717 0.638 0.927 0.941 0.869 0.752]
batch 6, [0.952 0.342 0.01  0.711 0.469 0.692 0.911 0.667]
batch 7, [0.69  0.255]


2025-05-13 14:14:13.456216: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


#### Combining two tensors into a joint dataset

In [ ]:
tf.random.set_seed(1)
t_x = tf.random.uniform([4, 3], dtype=tf.float32)
t_y = tf.range(4)
# ds_x = tf.data.Dataset.from_tensor_slices((t_x))
# ds_y = tf.data.Dataset.from_tensor_slices((t_y))
# ds_joint = tf.data.Dataset.zip((ds_x, ds_y))
ds_joint = tf.data.Dataset.from_tensor_slices((t_x, t_y)) # same output as zip(x, y)
for joint_elem in ds_joint:
    print("x is", joint_elem[0].numpy(),
          "and y is", joint_elem[1].numpy())

x is [0.165 0.901 0.631] and y is 0
x is [0.435 0.292 0.643] and y is 1
x is [0.976 0.435 0.66 ] and y is 2
x is [0.605 0.637 0.614] and y is 3


2025-05-13 14:21:05.455918: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


#### Transformations

In [71]:
ds_trans = ds_joint.map(lambda x, y: (x*2-1, y))
for elem_trans in ds_trans:
    print("x is", elem_trans[0].numpy(),
          "and y is", elem_trans[1].numpy())

x is [-0.67   0.803  0.262] and y is 0
x is [-0.131 -0.416  0.285] and y is 1
x is [ 0.952 -0.13   0.32 ] and y is 2
x is [0.21  0.273 0.229] and y is 3


2025-05-13 14:22:44.815928: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


#### Shuffle, batch and repeat (sequence matters!)

In [73]:
tf.random.set_seed(1)
ds = ds_joint.shuffle(buffer_size = len(t_x))
for elem in ds:
    print("x is", elem[0].numpy(),
          "and y is", elem[1].numpy())

x is [0.976 0.435 0.66 ] and y is 2
x is [0.435 0.292 0.643] and y is 1
x is [0.165 0.901 0.631] and y is 0
x is [0.605 0.637 0.614] and y is 3


2025-05-13 14:25:29.201473: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [75]:
ds = ds_joint.batch(batch_size=3,
                    drop_remainder=False)
batch_x, batch_y = next(iter(ds))
print('Batch-x:\n',batch_x.numpy())

Batch-x:
 [[0.165 0.901 0.631]
 [0.435 0.292 0.643]
 [0.976 0.435 0.66 ]]


In [76]:
ds = ds_joint.batch(3).repeat(2)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (3, 3) [0 1 2]
1 (1, 3) [3]
2 (3, 3) [0 1 2]
3 (1, 3) [3]


2025-05-13 14:32:30.002958: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [78]:
ds = ds_joint.batch(2).shuffle(4).repeat(2)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (2, 3) [0 1]
1 (2, 3) [2 3]
2 (2, 3) [0 1]
3 (2, 3) [2 3]


2025-05-13 14:34:08.340657: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


#### Tensorflow datasets

In [3]:
import tensorflow_datasets as tfds
print(tfds.list_builders()[:5])

2025-05-13 14:47:50.563800: W external/local_tsl/tsl/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata.google.internal".


['abstract_reasoning', 'accentdb', 'aeslc', 'aflw2k3d', 'ag_news_subset']


In [ ]:
# check page 445 of RM book for how to load tf datasets